# django dockerfile
FROM python:3.8.10

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE 1

ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip 

COPY requirements.txt /code/

RUN pip install -r requirements.txt

COPY . /code/

ENTRYPOINT ["python3", "manage.py", "runserver"]
CMD [ "0:8000" ]